### PR TITLE
Fix number_key click handler

### LINKED ISSUE #72: [问题]: paper1.12.2在菜单中按F切换副手出现报错，无其他影响
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2024-07-03 20:10:07)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Paper-1620 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 11.0.23

| TrMenu: 3.3.1a

### 🔍 详细的描述

如题

### 🗄 服务端日志

[20:08:57 ERROR]: [TrMenu] Error in onPacketInAsync()
[20:08:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.event.inventory.ClickType.SWAP_OFFHAND
[20:08:57 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:240)
[20:08:57 WARN]:        at org.bukkit.event.inventory.ClickType.valueOf(ClickType.java:6)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.ReceptacleClickType.toBukkitType(ReceptacleClickType.kt:84)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.ReceptacleClickType.isNumberKeyClick(ReceptacleClickType.kt:112)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.ReceptacleClickType.isKeyboardClick(ReceptacleClickType.kt:108)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.ReceptacleClickType.isItemMoveable(ReceptacleClickType.kt:124)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.ReceptacleInteractEvent.refresh(ReceptacleInteractEvent.kt:17)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.module.display.layout.Layout.initReceptacle$lambda$15$lambda$13(Layout.kt:80)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.module.display.layout.Layout.initReceptacle$lambda$15(Layout.kt:86)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.callEventClick(WindowReceptacle.kt:107)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowListener.clicked(WindowListener.kt:102)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowListener.onPacket(WindowListener.kt:52)
[20:08:57 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$visit$1$1.invoke(EventBus.kt:52)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$visit$1$1.invoke(EventBus.kt:52)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.event.InternalEventBus$Companion$impl$1$RegisteredListener.invoke(InternalEventBus.kt:81)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.event.InternalEventBus$Companion$impl$1.call(InternalEventBus.kt:62)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.event.InternalEventBus$Companion.call(InternalEventBus.kt:33)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.event.InternalEvent.call(InternalEvent.kt:12)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.common.event.CancelableInternalEvent.callIf(InternalEvent.kt:20)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.module.nms.TinyProtocol.onPacketInAsync(TinyProtocol.java:270)
[20:08:57 WARN]:        at me.arasple.mc.trmenu.taboolib.module.nms.TinyProtocol$PacketInterceptor.channelRead(TinyProtocol.java:474)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[20:08:57 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[20:08:57 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[20:08:57 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:08:57 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[20:08:57 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[20:08:57 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[20:08:57 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[20:08:57 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
[20:08:57 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[20:08:57 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[20:08:57 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[20:08:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

### ⚙ 配置文件

任意配置

### PR DESCRIPTION
**Pull request by Condordito**
This PR fixes #72 and corrects the click handler for the `number_key` action type<br>
Untitled

### CODE REVIEW

File: api/receptacle/src/main/kotlin/trplugins/menu/api/receptacle/ReceptacleClickType.kt [hunk 1]
```diff
@@ -25,58 +25,58 @@ enum class ReceptacleClickType(
 
     ALL(-1, -1),
 
-    LEFT(0, 0, ClickType.LEFT.name),
+    LEFT(0, 0, "LEFT"),
```
Comment (TheFloodDragon) [inline api/receptacle/src/main/kotlin/trplugins/menu/api/receptacle/ReceptacleClickType.kt:28]: Hope Bukkit won't change these names.
And whatever versions, it is the same.

**Review by TheFloodDragon — APPROVED** [review]
